name: GitHub Profile Summary

on:
  schedule:
    - cron: "15 1 * * *"

  workflow_dispatch:

permissions:
  contents: write

jobs:

  summary:

    runs-on: ubuntu-latest

    steps:

      - name: Generate Summary Cards

        uses: vn7n24fzkq/github-profile-summary-cards@release

        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

        with:
          USERNAME: Yash-Agarwal-4a5h