name: GitHub Activity Graph

on:
  workflow_dispatch:
  schedule:
    - cron: "0 0 * * *"

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Generate GitHub Activity Graph
        uses: Ashutosh00710/github-readme-activity-graph@main
        with:
          username: Yash-Agarwal-4a5h
          theme: github-dark
          output_file: dist/activity-graph.svg

      - name: Deploy Activity Graph
        uses: crazy-max/ghaction-github-pages@v4
        with:
          target_branch: output
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}