name: GitHub Profile Summary

on:
  workflow_dispatch:
  schedule:
    - cron: "0 1 * * *"

permissions:
  contents: write

jobs:
  summary:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Generate GitHub Profile Summary Cards
        uses: vn7n24fzkq/github-profile-summary-cards@release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          USERNAME: Yash-Agarwal-4a5h
          BRANCH_NAME: main

      - name: Commit generated cards
        uses: EndBug/add-and-commit@v9
        with:
          add: "profile-summary-card-output/*.svg"
          message: "chore: update GitHub profile summary cards"